server:
  port: 8081

spring:
  application:
    name: msgateway
#  cloud:
#    gateway:
#      routes:
#        - id: produtosModule
#          uri: lb://msprodutos
#          predicates:
#            - Path=/produtos/**
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    register-with-eureka: true
    fetch-registry: true
management:
  endpoints:
    web:
      exposure:
        include: gateway