server:
  port: 0

spring:
  application:
    name: msprodutos

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka